import type { NodelElementDefinition } from './types';
import { actionBindingSyntax, confirmationAttributes, preferredToggleIconNames, signalBindingDescription, signalsBindingDescription } from './values';
import { nodelButtonArgTypes, nodelButtonLayouts, nodelButtonSizes, nodelButtonTones, nodelButtonVariants } from '../component-values/nodel-button';

export const customControlElements: NodelElementDefinition[] = [
  {
    name: 'nodel-button',
    catalogue: true,
    defaultSignalTarget: 'active',
    aggregateSignalTargets: ['active', 'disabled'],
    description: 'Touch-sized action or state button.',
    attributes: [
      { name: 'variant', description: 'Button visual variant.', values: [...nodelButtonVariants] },
      { name: 'tone', description: 'Button visual tone.', values: [...nodelButtonTones] },
      { name: 'layout', description: 'Button child layout.', values: [...nodelButtonLayouts] },
      { name: 'size', description: 'Button size. Auto uses the context default.', values: [...nodelButtonSizes] },
      { name: 'action', description: 'Current-node action name to call on click.' },
      { name: 'actions', description: 'Action bindings in ActionName:phase format. Supported phases: click, press, release.' },
      { name: 'join', description: 'Shorthand that uses the same name for action and the default signal binding.' },
      { name: 'action-on', description: 'Legacy alias for a press-phase momentary action.', legacy: 'Use actions="ActionName:press" instead.' },
      { name: 'action-off', description: 'Legacy alias for a release-phase momentary action.', legacy: 'Use actions="ActionName:release" instead.' },
      { name: 'arg', description: 'Optional action argument value.' },
      { name: 'arg-type', description: 'Parser for arg.', values: [...nodelButtonArgTypes] },
      { name: 'disabled', description: 'Disable the button.' },
      { name: 'active', description: 'Mark the button active/pressed.' },
      { name: 'active-value', description: 'Optional active-state signal value when it differs from arg.' },
      { name: 'value', description: 'Contextual option value when this button is a child of nodel-segmented, nodel-select, or nodel-palette.' },
      { name: 'color', description: 'Contextual swatch colour when this button is a child of nodel-palette.' },
      { name: 'border', description: 'Contextual swatch border colour when this button is a child of nodel-palette.' },
      ...confirmationAttributes,
      { name: 'aria-label', description: 'Accessible label for icon-only or image-only buttons.' },
      { name: 'aria-labelledby', description: 'ID reference for the accessible button label.' },
      { name: 'title', description: 'Native button title text.' },
      { name: 'signal', description: signalBindingDescription('active') },
      { name: 'signals', description: signalsBindingDescription('active, label, disabled') }
    ],
    snippet: '<nodel-button action="ActionName">${}</nodel-button>'
  },
  {
    name: 'nodel-toggle',
    catalogue: true,
    defaultSignalTarget: 'state',
    aggregateSignalTargets: ['disabled'],
    description: 'Touch switch for boolean action/state controls, including partial feedback states.',
    attributes: [
      { name: 'action', description: 'Current-node action name to call on toggle.' },
      { name: 'actions', description: 'Action bindings in ActionName:phase format. Supported phases: toggle, on, off.' },
      { name: 'join', description: 'Shorthand that uses the same name for action and the default signal binding.' },
      { name: 'on-arg', description: 'Action argument sent when toggling on. Defaults to true.' },
      { name: 'off-arg', description: 'Action argument sent when toggling off. Defaults to false.' },
      { name: 'arg-type', description: 'Parser for on/off args.', values: ['boolean', 'string', 'number', 'json'] },
      { name: 'value', description: 'Current toggle state.', values: ['off', 'on', 'partially-off', 'partially-on'] },
      { name: 'on-value', description: 'Exact signal value that means on.' },
      { name: 'off-value', description: 'Exact signal value that means off.' },
      { name: 'partial-on-value', description: 'Exact signal value that means partially on.' },
      { name: 'partial-off-value', description: 'Exact signal value that means partially off.' },
      { name: 'label', description: 'Accessibility/fallback label. Use nodel-group label for visible captions.' },
      { name: 'aria-label', description: 'Explicit accessible label.' },
      { name: 'aria-labelledby', description: 'ID reference for the accessible label.' },
      { name: 'on-label', description: 'State label shown for on/partially-on.' },
      { name: 'off-label', description: 'State label shown for off/partially-off.' },
      { name: 'on-icon', description: 'State icon shown for on/partially-on.', values: preferredToggleIconNames },
      { name: 'off-icon', description: 'State icon shown for off/partially-off.', values: preferredToggleIconNames },
      { name: 'state-label', description: 'Show or hide visible state text. Hidden by default.', values: ['hide', 'show'] },
      { name: 'variant', description: 'On-state colour variant.', values: ['default', 'primary', 'success', 'info', 'warning', 'danger'] },
      { name: 'off-variant', description: 'Off-state colour variant. Default keeps the off state neutral.', values: ['default', 'primary', 'success', 'info', 'warning', 'danger'] },
      { name: 'tone', description: 'Switch track tone.', values: ['solid', 'soft', 'outline'] },
      { name: 'disabled', description: 'Disable the switch.' },
      { name: 'title', description: 'Native switch title text.' },
      ...confirmationAttributes,
      { name: 'signal', description: signalBindingDescription('state') },
      { name: 'signals', description: signalsBindingDescription('state, label, disabled') }
    ],
    snippet: '<nodel-group label="Theme">\n  <nodel-toggle action="SetTheme" signal="Theme" off-label="Light" on-label="Dark" off-icon="sun" on-icon="moon" state-label="show"></nodel-toggle>\n</nodel-group>'
  },
  {
    name: 'nodel-segmented',
    catalogue: true,
    defaultSignalTarget: 'value',
    aggregateSignalTargets: ['disabled'],
    description: 'Mutually exclusive option group using direct nodel-button children.',
    attributes: [
      { name: 'action', description: 'Current-node action name called when an option is selected.' },
      { name: 'actions', description: 'Action bindings in ActionName:phase format. Supported phase: select.' },
      { name: 'join', description: 'Shorthand that uses the same name for action and the default signal binding.' },
      { name: 'arg-type', description: 'Parser for option values.', values: ['string', 'number', 'boolean', 'json'] },
      { name: 'value', description: 'Current selected option value.' },
      { name: 'variant', description: 'Active option colour variant.', values: ['default', 'primary', 'success', 'info', 'warning', 'danger'] },
      { name: 'tone', description: 'Active option tone.', values: ['solid', 'soft', 'outline'] },
      { name: 'orientation', description: 'Option group orientation.', values: ['horizontal', 'vertical'] },
      { name: 'disabled', description: 'Disable the group.' },
      { name: 'allow-deselect', description: 'Allow tapping the active option to clear selection.' },
      { name: 'label', description: 'Accessible group label.' },
      { name: 'aria-label', description: 'Explicit accessible group label.' },
      { name: 'aria-labelledby', description: 'ID reference for the accessible group label.' },
      { name: 'options-signal', description: 'SignalName[.path] source for dynamic option arrays. Accepts scalars, { value, label }, and v1 { key, value } entries.' },
      { name: 'options-loading-label', description: 'Status text while dynamic options are loading. Default: Loading options...' },
      { name: 'options-empty-label', description: 'Status text for a valid empty dynamic option list. Default: No options.' },
      { name: 'options-error-label', description: 'Status text when dynamic options are unavailable or malformed. Default: Options unavailable.' },
      ...confirmationAttributes,
      { name: 'signal', description: signalBindingDescription('value') },
      { name: 'signals', description: `${signalsBindingDescription('value, label, disabled, options')} The options target only supports last-value bindings; options(any) and options(all) are invalid.` }
    ],
    snippet: '<nodel-group label="Source">\n  <nodel-segmented action="SetSource" signal="Source">\n    <nodel-button value="HDMI 1">HDMI 1</nodel-button>\n    <nodel-button value="HDMI 2">HDMI 2</nodel-button>\n  </nodel-segmented>\n</nodel-group>'
  },
  {
    name: 'nodel-select',
    catalogue: true,
    defaultSignalTarget: 'value',
    aggregateSignalTargets: ['disabled'],
    description: 'Touch picker for larger option sets using nodel-button options.',
    attributes: [
      { name: 'label', description: 'Accessibility/fallback label. Use nodel-group label for visible captions.' },
      { name: 'aria-label', description: 'Explicit accessible label.' },
      { name: 'aria-labelledby', description: 'ID reference for the accessible label.' },
      { name: 'placeholder', description: 'Text shown when no value is selected.' },
      { name: 'value', description: 'Current selected value.' },
      { name: 'action', description: 'Current-node action called when an option is selected.' },
      { name: 'actions', description: 'Action bindings in ActionName:phase format. Supported phase: select.' },
      { name: 'join', description: 'Shorthand that uses the same name for action and value signal.' },
      { name: 'arg-type', description: 'Parser for selected option values.', values: ['string', 'number', 'boolean', 'json'] },
      { name: 'variant', description: 'Picker visual variant.', values: ['default', 'primary', 'success', 'info', 'warning', 'danger', 'ghost'] },
      { name: 'tone', description: 'Picker visual tone.', values: ['solid', 'soft', 'outline'] },
      { name: 'disabled', description: 'Disable the picker.' },
      { name: 'allow-deselect', description: 'Allow selecting the active option to clear value.' },
      { name: 'open', description: 'Start with the option panel open.' },
      { name: 'placement', description: 'Option panel placement. Auto uses visual-viewport space.', values: ['auto', 'bottom', 'top'] },
      { name: 'options-signal', description: 'SignalName[.path] source for dynamic option arrays. Accepts scalars, { value, label }, and v1 { key, value } entries.' },
      { name: 'options-loading-label', description: 'Status text while dynamic options are loading. Default: Loading options...' },
      { name: 'options-empty-label', description: 'Status text for a valid empty dynamic option list. Default: No options.' },
      { name: 'options-error-label', description: 'Status text when dynamic options are unavailable or malformed. Default: Options unavailable.' },
      ...confirmationAttributes,
      { name: 'signal', description: signalBindingDescription('value') },
      { name: 'signals', description: `${signalsBindingDescription('value, label, disabled, options')} The options target only supports last-value bindings; options(any) and options(all) are invalid.` }
    ],
    snippet: '<nodel-group label="Source">\n  <nodel-select action="SetSource" signal="Source">\n    <nodel-button value="HDMI 1">HDMI 1</nodel-button>\n    <nodel-button value="HDMI 2">HDMI 2</nodel-button>\n  </nodel-select>\n</nodel-group>'
  },
  {
    name: 'nodel-fader',
    catalogue: true,
    defaultSignalTarget: 'value',
    aggregateSignalTargets: ['disabled'],
    description: 'Touch-first level fader with optional increment buttons and compound rail content.',
    attributes: [
      { name: 'orientation', description: 'Fader orientation.', values: ['vertical', 'horizontal'] },
      { name: 'compound-align', description: 'Compound rail alignment. Prefer bottom/center/top; end/right, start/left, and middle are compatibility aliases.', values: ['bottom', 'center', 'top', 'end', 'right', 'start', 'left', 'middle'] },
      { name: 'variant', description: 'Fader fill colour variant.', values: ['default', 'primary', 'success', 'info', 'warning', 'danger', 'ghost'] },
      { name: 'tone', description: 'Fader rail/fill tone.', values: ['solid', 'soft', 'outline'] },
      { name: 'min', description: 'Minimum value.', defaultDescription: 'Derived from unit: 0 for percent/none, -60 for dB.' },
      { name: 'max', description: 'Maximum value.', defaultDescription: 'Derived from unit: 100 for percent/none, 10 for dB.' },
      { name: 'step', description: 'Positive finite value step. Non-positive or invalid input falls back to 1.', defaultValue: '1' },
      { name: 'unit', description: 'Value display unit and default range.', values: ['percent', 'db', 'none'], defaultValue: 'percent' },
      { name: 'nudge', description: 'Positive finite increment for +/- controls. Invalid input falls back to step; presence enables increment buttons.' },
      { name: 'increment', description: 'Show +/- increment controls.' },
      { name: 'action', description: 'Current-node action name called on change.' },
      { name: 'actions', description: 'Action bindings in ActionName:phase format. Supported phases: live, commit.' },
      { name: 'join', description: 'Shorthand that uses the same name for action and the default signal binding.' },
      { name: 'arg-type', description: 'Parser for action arg.', values: ['number', 'string', 'json'] },
      { name: 'value', description: 'Current fader value.' },
      { name: 'disabled', description: 'Disable dragging and increment controls.' },
      { name: 'readout', description: 'Show or hide numeric value readout.', values: ['show', 'hide'] },
      { name: 'label', description: 'Accessibility/fallback label. Use nodel-group label for visible captions.' },
      { name: 'aria-label', description: 'Explicit accessible label.' },
      { name: 'aria-labelledby', description: 'ID reference for the accessible label.' },
      { name: 'title', description: 'Native slider title text.' },
      { name: 'live-interval', description: 'Throttled live action interval. Finite input is clamped to at least 50ms; invalid input falls back to 250ms.', defaultValue: '250', numeric: { min: 50, unit: 'ms', clamp: true } },
      ...confirmationAttributes,
      { name: 'signal', description: signalBindingDescription('value') },
      { name: 'signals', description: signalsBindingDescription('value, label, disabled') }
    ],
    snippet: '<nodel-group label="Volume">\n  <nodel-fader action="SetVolume" signal="Volume" nudge="5">\n    ${}\n  </nodel-fader>\n</nodel-group>'
  },
  {
    name: 'nodel-stepper',
    catalogue: true,
    defaultSignalTarget: 'value',
    aggregateSignalTargets: ['disabled'],
    description: 'Precise touch numeric increment/decrement control.',
    attributes: [
      { name: 'label', description: 'Accessibility/fallback label. Use nodel-group label for visible captions.' },
      { name: 'aria-label', description: 'Explicit accessible label.' },
      { name: 'aria-labelledby', description: 'ID reference for the accessible label.' },
      { name: 'value', description: 'Current numeric value.' },
      { name: 'min', description: 'Minimum value.', defaultValue: '0' },
      { name: 'max', description: 'Maximum value.', defaultValue: '100' },
      { name: 'step', description: 'Positive finite increment. Non-positive or invalid input falls back to 1.', defaultValue: '1' },
      { name: 'unit', description: 'Optional value unit formatting.', values: ['percent', 'db', 'none'] },
      { name: 'prefix', description: 'Display prefix for plain numbers.' },
      { name: 'suffix', description: 'Display suffix for plain numbers.' },
      { name: 'precision', description: 'Decimal precision for display. An integer prefix is parsed, then clamped to 0..10.', syntax: 'integer-prefixed text' },
      { name: 'repeat', description: 'Hold repeat mode.', values: ['hold', 'off'], defaultValue: 'hold' },
      { name: 'repeat-delay', description: 'Delay before hold repeat begins. Finite input is clamped to at least 0ms; invalid input falls back to 300ms.', defaultValue: '300', numeric: { min: 0, unit: 'ms', clamp: true } },
      { name: 'repeat-interval', description: 'Hold repeat interval. Finite input is clamped to at least 50ms; invalid input falls back to 200ms.', defaultValue: '200', numeric: { min: 50, unit: 'ms', clamp: true } },
      { name: 'action', description: 'Current-node action called on value changes.' },
      { name: 'actions', description: 'Action bindings. Supported phases: live, commit, increase, decrease.' },
      { name: 'join', description: 'Shorthand that uses the same name for action and value signal.' },
      { name: 'arg-type', description: 'Parser for emitted value.', values: ['number', 'string', 'json'] },
      { name: 'variant', description: 'Stepper visual variant.', values: ['default', 'primary', 'success', 'info', 'warning', 'danger', 'ghost'] },
      { name: 'tone', description: 'Stepper button tone.', values: ['solid', 'soft', 'outline'] },
      { name: 'disabled', description: 'Disable both buttons.' },
      { name: 'readout', description: 'Show or hide the numeric readout.', values: ['show', 'hide'] },
      ...confirmationAttributes,
      { name: 'signal', description: signalBindingDescription('value') },
      { name: 'signals', description: signalsBindingDescription('value, label, disabled') }
    ],
    snippet: '<nodel-group label="Temperature">\n  <nodel-stepper action="SetTemp" signal="Temp" min="16" max="28" step="0.5" suffix="C"></nodel-stepper>\n</nodel-group>'
  },
  {
    name: 'nodel-pad',
    catalogue: true,
    aggregateSignalTargets: ['disabled', 'center-disabled'],
    description: 'Directional touch pad with click or momentary press/release modes.',
    attributes: [
      { name: 'label', description: 'Accessibility/fallback label. Use nodel-group label for visible captions.' },
      { name: 'aria-label', description: 'Explicit accessible label.' },
      { name: 'aria-labelledby', description: 'ID reference for the accessible label.' },
      { name: 'center', description: 'Centre button behavior.', values: ['auto', 'show', 'hide', 'disabled'] },
      { name: 'press-mode', description: 'Button action mode.', values: ['click', 'momentary'] },
      { name: 'action', description: 'Shared action called with direction arg.' },
      { name: 'actions', description: 'Shared action bindings. Supported phases: click, press, release.' },
      { name: 'arg-type', description: 'Parser for direction arguments.', values: ['string', 'json'] },
      { name: 'up-action', description: 'Action for the up button.' },
      { name: 'down-action', description: 'Action for the down button.' },
      { name: 'left-action', description: 'Action for the left button.' },
      { name: 'right-action', description: 'Action for the right button.' },
      { name: 'center-action', description: 'Action for the centre button.' },
      { name: 'up-actions', description: 'Action bindings for the up button. Supported phases: click, press, release.', syntax: actionBindingSyntax },
      { name: 'down-actions', description: 'Action bindings for the down button. Supported phases: click, press, release.', syntax: actionBindingSyntax },
      { name: 'left-actions', description: 'Action bindings for the left button. Supported phases: click, press, release.', syntax: actionBindingSyntax },
      { name: 'right-actions', description: 'Action bindings for the right button. Supported phases: click, press, release.', syntax: actionBindingSyntax },
      { name: 'center-actions', description: 'Action bindings for the centre button. Supported phases: click, press, release.', syntax: actionBindingSyntax },
      { name: 'up-arg', description: 'Action argument for the up button.', defaultValue: 'up' },
      { name: 'down-arg', description: 'Action argument for the down button.', defaultValue: 'down' },
      { name: 'left-arg', description: 'Action argument for the left button.', defaultValue: 'left' },
      { name: 'right-arg', description: 'Action argument for the right button.', defaultValue: 'right' },
      { name: 'center-arg', description: 'Action argument for the centre button.', defaultValue: 'center' },
      { name: 'up-label', description: 'Accessible label for the up button.', defaultDescription: 'Derived: pad accessible label plus up, otherwise Up.' },
      { name: 'down-label', description: 'Accessible label for the down button.', defaultDescription: 'Derived: pad accessible label plus down, otherwise Down.' },
      { name: 'left-label', description: 'Accessible label for the left button.', defaultDescription: 'Derived: pad accessible label plus left, otherwise Left.' },
      { name: 'right-label', description: 'Accessible label for the right button.', defaultDescription: 'Derived: pad accessible label plus right, otherwise Right.' },
      { name: 'center-label', description: 'Accessible label for the centre button.', defaultDescription: 'Derived: pad accessible label plus center, otherwise Center.' },
      { name: 'variant', description: 'Pad visual variant.', values: ['default', 'primary', 'success', 'info', 'warning', 'danger', 'ghost'] },
      { name: 'tone', description: 'Pad button tone.', values: ['solid', 'soft', 'outline'] },
      { name: 'disabled', description: 'Disable the whole pad.' },
      { name: 'center-disabled', description: 'Disable only the centre button.' },
      ...confirmationAttributes,
      { name: 'signal', description: 'Explicit signal binding in SignalName[.path]:target format. Supported targets: disabled, label, center-disabled.' },
      { name: 'signals', description: signalsBindingDescription('disabled, label, center-disabled') }
    ],
    snippet: '<nodel-group label="Navigate">\n  <nodel-pad action="Navigate" center="show"></nodel-pad>\n</nodel-group>'
  },
  {
    name: 'nodel-readout',
    catalogue: true,
    defaultSignalTarget: 'value',
    description: 'Read-only touch value/status tile with optional bar, ring, or status visuals.',
    attributes: [
      { name: 'label', description: 'Accessibility/fallback label. Use nodel-group label for visible captions.' },
      { name: 'aria-label', description: 'Explicit accessible label.' },
      { name: 'aria-labelledby', description: 'ID reference for the accessible label.' },
      { name: 'value', description: 'Current displayed value.' },
      { name: 'type', description: 'Value type.', values: ['text', 'number', 'percent', 'db', 'boolean', 'duration'], defaultValue: 'text' },
      { name: 'visual', description: 'Graphical representation.', values: ['none', 'bar', 'ring', 'status'], defaultDescription: 'Derived: status for boolean, none otherwise.' },
      { name: 'min', description: 'Minimum numeric value for visuals.', defaultDescription: 'Derived: 0 except -60 for dB.' },
      { name: 'max', description: 'Maximum numeric value for visuals.', defaultDescription: 'Derived: 100 except 10 for dB.' },
      { name: 'unit', description: 'Range unit used by numeric visuals when type is number.', values: ['percent', 'db', 'none'] },
      { name: 'prefix', description: 'Display prefix.' },
      { name: 'suffix', description: 'Display suffix.' },
      { name: 'precision', description: 'Decimal precision. An integer prefix is parsed, then clamped to 0..10.', syntax: 'integer-prefixed text' },
      { name: 'on-value', description: 'Exact value treated as on for boolean type.' },
      { name: 'off-value', description: 'Exact value treated as off for boolean type.' },
      { name: 'on-label', description: 'Boolean on-state display label.', defaultValue: 'On' },
      { name: 'off-label', description: 'Boolean off-state display label.', defaultValue: 'Off' },
      { name: 'warn', description: 'Warning threshold for numeric status visuals.', defaultDescription: 'Derived: 80% of the effective range.' },
      { name: 'danger', description: 'Danger threshold for numeric status visuals.', defaultDescription: 'Derived: 95% of the effective range.' },
      { name: 'empty', description: 'Text displayed for an empty or invalid value.', defaultValue: '--' },
      { name: 'variant', description: 'Readout visual variant.', values: ['default', 'primary', 'success', 'info', 'warning', 'danger', 'ghost'] },
      { name: 'tone', description: 'Readout value/visual tone.', values: ['solid', 'soft', 'outline'] },
      { name: 'signal', description: signalBindingDescription('value') },
      { name: 'signals', description: signalsBindingDescription('value, label, variant, suffix, prefix') }
    ],
    snippet: '<nodel-group label="Brightness">\n  <nodel-readout type="percent" visual="ring" value="72"></nodel-readout>\n</nodel-group>'
  },
  {
    name: 'nodel-palette',
    catalogue: true,
    defaultSignalTarget: 'value',
    aggregateSignalTargets: ['disabled'],
    description: 'Swatch-first colour picker with predefined colour buttons and optional native custom colour input.',
    attributes: [
      { name: 'label', description: 'Accessibility/fallback label. Use nodel-group label for visible captions.' },
      { name: 'aria-label', description: 'Explicit accessible label.' },
      { name: 'aria-labelledby', description: 'ID reference for the accessible label.' },
      { name: 'value', description: 'Current selected colour or preset value.' },
      { name: 'action', description: 'Current-node action called when a swatch is selected.' },
      { name: 'actions', description: 'Action bindings. Supported phases: select, live, commit.' },
      { name: 'join', description: 'Shorthand that uses the same name for action and value signal.' },
      { name: 'arg-type', description: 'Parser for selected values.', values: ['string', 'json'] },
      { name: 'columns', description: 'Internal swatch column count. An integer prefix is parsed, then clamped to 1..12.', syntax: 'integer-prefixed text', numeric: { min: 1, max: 12, clamp: true, normalizesToInteger: true } },
      { name: 'shape', description: 'Swatch shape.', values: ['square', 'rounded', 'circle'], defaultValue: 'rounded' },
      { name: 'picker', description: 'Optional custom colour picker.', values: ['off', 'native'], defaultValue: 'off' },
      { name: 'value-field', description: 'Custom colour value feedback mode.', values: ['readonly', 'editable', 'hidden'], defaultValue: 'readonly' },
      { name: 'format', description: 'Action payload colour format.', values: ['hex', 'rgb', 'hsl', 'hsv'] },
      { name: 'custom-label', description: 'Visible label for the native custom colour picker. Hidden when omitted.' },
      { name: 'live', description: 'Dispatch throttled custom-picker input updates.' },
      { name: 'live-interval', description: 'Live update interval. An integer prefix is parsed, then clamped to 50..1000ms.', syntax: 'integer-prefixed text', defaultValue: '100', numeric: { min: 50, max: 1000, unit: 'ms', clamp: true, normalizesToInteger: true } },
      { name: 'show-labels', description: 'Swatch label visibility.', values: ['auto', 'show', 'hide'] },
      { name: 'variant', description: 'Palette visual variant.', values: ['default', 'primary', 'success', 'info', 'warning', 'danger', 'ghost'] },
      { name: 'tone', description: 'Palette swatch/custom-control tone.', values: ['solid', 'soft', 'outline'] },
      { name: 'disabled', description: 'Disable all swatches.' },
      { name: 'allow-deselect', description: 'Allow selecting the current swatch to clear the value.' },
      ...confirmationAttributes,
      { name: 'signal', description: signalBindingDescription('value') },
      { name: 'signals', description: signalsBindingDescription('value, label, disabled, custom-color') }
    ],
    snippet: '<nodel-group label="Colour">\n  <nodel-palette action="SetColour" signal="Colour" picker="native">\n    <nodel-button value="#ff0000" color="#ff0000">Red</nodel-button>\n    <nodel-button value="#00ff00" color="#00ff00">Green</nodel-button>\n    <nodel-button value="#0000ff" color="#0000ff">Blue</nodel-button>\n  </nodel-palette>\n</nodel-group>'
  },
];
