import type { NodelAttributeDefinition } from './types';


export type AttributeDefaultMetadata = Pick<NodelAttributeDefinition, 'defaultValue' | 'defaultDescription'>;

// Only record a default when omission has defined runtime behaviour. Unconfigured inputs remain absent.
export const attributeDefaultMetadata: Record<string, AttributeDefaultMetadata> = {
  'nodel-description.collapsed-height': { defaultValue: '8rem' },
  'nodel-description.open': { defaultValue: 'false' },
  'nodel-node-list.scope': { defaultValue: 'local' },
  'nodel-node-list.poll-interval': { defaultDescription: 'Derived: 2000 ms for local scope and 10000 ms for network scope.' },
  'nodel-node-list.page-size': { defaultValue: '20' },
  'nodel-add-node.redirect': { defaultValue: 'true' },
  'nodel-add-node.recipes': { defaultValue: 'true' },
  'nodel-add-node.duplicate': { defaultValue: 'true' },
  'nodel-editor.default-file': { defaultValue: 'script.py' },
  'nodel-app.theme': { defaultDescription: 'Derived: stored theme preference, otherwise the system theme.' },
  'nodel-app.offline-mode': { defaultValue: 'modal' },
  'nodel-toolbar.title': { defaultDescription: 'Derived: app signal title or discovered node name when available.' },
  'nodel-toolbar.icon-alt': { defaultDescription: 'Derived: title.' },
  'nodel-toolbar.show-host-icon': { defaultValue: 'false' },
  'nodel-page.title': { defaultDescription: 'Derived: Page for parent navigation when neither title nor nav-label is configured.' },
  'nodel-page.nav-label': { defaultDescription: 'Derived: title, otherwise Page.' },
  'nodel-page.nav-id': { defaultDescription: 'Derived: slugged navigation label/title, with a numeric suffix when needed for uniqueness.' },
  'nodel-page.arg-type': { defaultValue: 'string' },
  'nodel-footer.fixed': { defaultValue: 'false' },
  'nodel-group.surface': { defaultValue: 'card' },
  'nodel-group.padding': { defaultValue: 'default' },
  'nodel-column.sm': { defaultDescription: 'No override: inherits the base span.' },
  'nodel-column.md': { defaultDescription: 'No override: inherits the preceding breakpoint span.' },
  'nodel-column.lg': { defaultDescription: 'No override: inherits the preceding breakpoint span.' },
  'nodel-column.xl': { defaultDescription: 'No override: inherits the preceding breakpoint span.' },
  'nodel-column.2xl': { defaultDescription: 'No override: inherits the preceding breakpoint span.' },
  'nodel-column.order': { defaultValue: '0' },
  'nodel-column.sm-order': { defaultDescription: 'No override: inherits the base order.' },
  'nodel-column.md-order': { defaultDescription: 'No override: inherits the preceding breakpoint order.' },
  'nodel-column.lg-order': { defaultDescription: 'No override: inherits the preceding breakpoint order.' },
  'nodel-column.xl-order': { defaultDescription: 'No override: inherits the preceding breakpoint order.' },
  'nodel-column.2xl-order': { defaultDescription: 'No override: inherits the preceding breakpoint order.' },
  'nodel-control-grid.sm': { defaultDescription: 'No override: inherits the base column count.' },
  'nodel-control-grid.md': { defaultDescription: 'No override: inherits the preceding breakpoint column count.' },
  'nodel-control-grid.lg': { defaultDescription: 'No override: inherits the preceding breakpoint column count.' },
  'nodel-control-grid.xl': { defaultDescription: 'No override: inherits the preceding breakpoint column count.' },
  'nodel-control-grid.2xl': { defaultDescription: 'No override: inherits the preceding breakpoint column count.' },
  'nodel-button.variant': { defaultValue: 'default' },
  'nodel-button.tone': { defaultValue: 'solid' },
  'nodel-button.layout': { defaultValue: 'inline' },
  'nodel-button.size': { defaultValue: 'auto' },
  'nodel-button.arg-type': { defaultValue: 'string' },
  'nodel-button.active': { defaultValue: 'false' },
  'nodel-button.disabled': { defaultValue: 'false' },
  'nodel-button.confirm-title': { defaultDescription: 'Derived: Confirm action for direct actions; parent controls may provide contextual titles.' },
  'nodel-button.confirm-text': { defaultDescription: 'Derived from the button label/action unless confirm supplies text; parent controls may provide contextual text.' },
  'nodel-button.confirm-tone': { defaultDescription: 'Derived: warning for direct actions; parent controls may provide a contextual tone.' },
  'nodel-toggle.on-arg': { defaultValue: 'true' },
  'nodel-toggle.off-arg': { defaultValue: 'false' },
  'nodel-toggle.arg-type': { defaultValue: 'boolean' },
  'nodel-toggle.value': { defaultValue: 'off' },
  'nodel-toggle.variant': { defaultValue: 'success' },
  'nodel-toggle.off-variant': { defaultValue: 'default' },
  'nodel-toggle.tone': { defaultValue: 'solid' },
  'nodel-toggle.state-label': { defaultValue: 'hide' },
  'nodel-toggle.disabled': { defaultValue: 'false' },
  'nodel-toggle.on-label': { defaultValue: 'On' },
  'nodel-toggle.off-label': { defaultValue: 'Off' },
  'nodel-toggle.confirm-title': { defaultValue: 'Confirm toggle' },
  'nodel-toggle.confirm-text': { defaultDescription: 'Derived from the toggle label and requested on/off state unless confirm supplies text.' },
  'nodel-toggle.confirm-tone': { defaultDescription: 'Derived: success when turning on; info when turning off.' },
  'nodel-segmented.arg-type': { defaultValue: 'string' },
  'nodel-segmented.variant': { defaultValue: 'primary' },
  'nodel-segmented.tone': { defaultValue: 'solid' },
  'nodel-segmented.orientation': { defaultValue: 'horizontal' },
  'nodel-segmented.disabled': { defaultValue: 'false' },
  'nodel-segmented.allow-deselect': { defaultValue: 'false' },
  'nodel-segmented.options-loading-label': { defaultValue: 'Loading options...' },
  'nodel-segmented.options-empty-label': { defaultValue: 'No options' },
  'nodel-segmented.options-error-label': { defaultValue: 'Options unavailable' },
  'nodel-segmented.confirm-title': { defaultValue: 'Confirm selection' },
  'nodel-segmented.confirm-text': { defaultDescription: 'Derived from the selected option unless confirm supplies text.' },
  'nodel-segmented.confirm-tone': { defaultDescription: 'info when confirmation is active.' },
  'nodel-select.arg-type': { defaultValue: 'string' },
  'nodel-select.variant': { defaultValue: 'default' },
  'nodel-select.tone': { defaultValue: 'solid' },
  'nodel-select.disabled': { defaultValue: 'false' },
  'nodel-select.allow-deselect': { defaultValue: 'false' },
  'nodel-select.open': { defaultValue: 'false' },
  'nodel-select.placement': { defaultValue: 'auto' },
  'nodel-select.placeholder': { defaultDescription: 'Derived: selected option/value, dynamic state, or Select.' },
  'nodel-select.options-loading-label': { defaultValue: 'Loading options...' },
  'nodel-select.options-empty-label': { defaultValue: 'No options' },
  'nodel-select.options-error-label': { defaultValue: 'Options unavailable' },
  'nodel-select.confirm-title': { defaultValue: 'Confirm selection' },
  'nodel-select.confirm-text': { defaultDescription: 'Derived from the selected option unless confirm supplies text.' },
  'nodel-select.confirm-tone': { defaultDescription: 'info when confirmation is active.' },
  'nodel-fader.orientation': { defaultValue: 'vertical' },
  'nodel-fader.compound-align': { defaultValue: 'bottom' },
  'nodel-fader.variant': { defaultValue: 'default' },
  'nodel-fader.tone': { defaultValue: 'solid' },
  'nodel-fader.increment': { defaultValue: 'false' },
  'nodel-fader.disabled': { defaultValue: 'false' },
  'nodel-fader.readout': { defaultValue: 'show' },
  'nodel-fader.value': { defaultDescription: 'Derived: effective minimum.' },
  'nodel-fader.confirm-title': { defaultValue: 'Confirm value' },
  'nodel-fader.confirm-text': { defaultDescription: 'Derived from the label and formatted value unless confirm supplies text.' },
  'nodel-fader.confirm-tone': { defaultDescription: 'info when confirmation is active.' },
  'nodel-stepper.unit': { defaultValue: 'none' },
  'nodel-stepper.variant': { defaultValue: 'default' },
  'nodel-stepper.tone': { defaultValue: 'solid' },
  'nodel-stepper.arg-type': { defaultValue: 'number' },
  'nodel-stepper.disabled': { defaultValue: 'false' },
  'nodel-stepper.readout': { defaultValue: 'show' },
  'nodel-stepper.value': { defaultDescription: 'Derived: effective minimum.' },
  'nodel-stepper.confirm-title': { defaultValue: 'Confirm value' },
  'nodel-stepper.confirm-text': { defaultDescription: 'Derived from the label and formatted value unless confirm supplies text.' },
  'nodel-stepper.confirm-tone': { defaultDescription: 'info when confirmation is active.' },
  'nodel-pad.center': { defaultValue: 'auto' },
  'nodel-pad.press-mode': { defaultValue: 'click' },
  'nodel-pad.arg-type': { defaultValue: 'string' },
  'nodel-pad.variant': { defaultValue: 'default' },
  'nodel-pad.tone': { defaultValue: 'solid' },
  'nodel-pad.disabled': { defaultValue: 'false' },
  'nodel-pad.center-disabled': { defaultValue: 'false' },
  'nodel-pad.confirm-title': { defaultValue: 'Confirm action' },
  'nodel-pad.confirm-text': { defaultDescription: 'Derived from the selected direction label unless confirm supplies text.' },
  'nodel-pad.confirm-tone': { defaultDescription: 'info when confirmation is active.' },
  'nodel-readout.unit': { defaultValue: 'percent' },
  'nodel-readout.variant': { defaultValue: 'default' },
  'nodel-readout.tone': { defaultValue: 'solid' },
  'nodel-palette.arg-type': { defaultValue: 'string' },
  'nodel-palette.format': { defaultValue: 'hex' },
  'nodel-palette.show-labels': { defaultValue: 'auto' },
  'nodel-palette.variant': { defaultValue: 'default' },
  'nodel-palette.tone': { defaultValue: 'solid' },
  'nodel-palette.disabled': { defaultValue: 'false' },
  'nodel-palette.live': { defaultValue: 'false' },
  'nodel-palette.allow-deselect': { defaultValue: 'false' },
  'nodel-palette.confirm-title': { defaultValue: 'Confirm colour' },
  'nodel-palette.confirm-text': { defaultDescription: 'Derived from the selected colour unless confirm supplies text.' },
  'nodel-palette.confirm-tone': { defaultDescription: 'info when confirmation is active.' },
  'nodel-meter.value': { defaultDescription: 'Derived: effective minimum.' },
  'nodel-image.fit': { defaultValue: 'contain' },
  'nodel-image.shape': { defaultValue: 'rounded' },
  'nodel-image.size': { defaultValue: 'auto' },
  'nodel-icon.name': { defaultValue: 'image' },
  'nodel-icon.tone': { defaultValue: 'default' },
  'nodel-icon.size': { defaultValue: 'auto' },
  'nodel-status-indicator.tone': { defaultValue: 'success' },
  'nodel-status-indicator.off-tone': { defaultValue: 'off' },
  'nodel-status-indicator.partial-tone': { defaultValue: 'warning' },
  'nodel-status-indicator.show-state-label': { defaultValue: 'false' },
  'nodel-status-indicator.on-label': { defaultValue: 'On' },
  'nodel-status-indicator.off-label': { defaultValue: 'Off' },
  'nodel-status-indicator.partial-on-label': { defaultValue: 'Partially on' },
  'nodel-status-indicator.partial-off-label': { defaultValue: 'Partially off' },
  'nodel-status.surface': { defaultValue: 'card' },
  'nodel-status.padding': { defaultValue: 'default' },
  'nodel-status.tone': { defaultValue: 'soft' },
  'nodel-status.state': { defaultDescription: 'Derived from state-map, level, structured value, or recognized value text.' },
  'nodel-collapse.label': { defaultValue: 'Details' },
  'nodel-collapse.open': { defaultValue: 'false' },
  'nodel-text.tone': { defaultValue: 'muted' },
  'nodel-text.size': { defaultValue: 'sm' },
  'nodel-text.surface': { defaultValue: 'none' },
  'nodel-title.level': { defaultValue: '1' },
  'nodel-title.tone': { defaultValue: 'default' },
  'nodel-markdown.max-height': { defaultValue: 'none' },
  'nodel-clock.format': { defaultValue: 'time' },
  'nodel-clock.hour12': { defaultValue: 'auto' },
  'nodel-host-icon.host': { defaultDescription: 'Derived: window.location.host.' },
  'nodel-host-icon.icon-host': { defaultDescription: 'Derived: host.' },
  'nodel-host-icon.title': { defaultDescription: 'Derived: host, or Browse this host when href is valid.' },
  'nodel-host-icon.alt': { defaultDescription: 'Derived: host.' }
};
