import './components/nodel-app';
import './components/nodel-toolbar';
import './components/nodel-page';
import './components/nodel-row';
import './components/nodel-column';
import './components/nodel-control-grid';
import './components/nodel-control-space';
import './components/nodel-group';
import './components/nodel-template';
import './components/nodel-button';
import './components/nodel-toggle';
import './components/nodel-segmented';
import './components/nodel-select';
import './components/nodel-meter';
import './components/nodel-fader';
import './components/nodel-stepper';
import './components/nodel-pad';
import './components/nodel-readout';
import './components/nodel-palette';
import './components/nodel-image';
import './components/nodel-icon';
import './components/nodel-qrcode';
import './components/nodel-status-indicator';
import './components/nodel-status';
import './components/nodel-collapse';
import './components/nodel-description';
import './components/nodel-text';
import './components/nodel-title';
import './components/nodel-host-icon';
import './components/nodel-node-list';
import './components/nodel-add-node';
import './components/nodel-node-menu';
import './components/nodel-diagnostics';
import './components/nodel-host-log';
import './components/nodel-diagnostic-charts';
import './components/nodel-toolkit';
import './components/nodel-console';
import './components/nodel-log';
import './components/nodel-actsig';
import './components/nodel-params';
import './components/nodel-bindings';
import './components/nodel-editor';
import './components/nodel-theme-toggle';
import './components/nodel-toast-host';
import './components/nodel-confirm-host';

import { updateHostFavicon } from './icons/favicon';
import { bootstrapSignalVisibilityBindings } from './data/signal-bindings';
import { bootstrapJsViews } from './jsviews/jsviews-runtime';

updateHostFavicon();
bootstrapSignalVisibilityBindings();

void bootstrapJsViews().catch((error) => {
  console.error('JsViews bootstrap failed', error);
});
